// Generated by schema-gen - DO NOT EDIT

import { useQuery, queryOptions, useMutation } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';
import { apiClient } from '../lib/client';
import { toFormData } from '../lib/form-data';
import type { CreatePetRequest, CreateUserRequest, FileMetadata, FileUploadRequest, FileUploadResponse, HealthStatus, PatchPetRequest, Pet, PetList, PhotoUploadRequest, PhotoUploadResponse, UpdatePetRequest, User } from './types';
import type { PetStatus, UserRole } from './enums';


// ============ GET /health ============

export const getGetHealthQueryKey = () => ['getHealth'] as const;

export type GetHealthQueryKey = ReturnType<typeof getGetHealthQueryKey>;

export const getGetHealthQueryOptions = <TData = HealthStatus>(
  options?: Partial<UseQueryOptions<HealthStatus, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetHealthQueryKey(),
    queryFn: () => apiClient('/health'),
    ...options,
  });

/**
 * Health check endpoint
 * @path GET /health
 */
export const useGetHealth = <TData = HealthStatus>(
  options?: Partial<UseQueryOptions<HealthStatus, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetHealthQueryOptions(options));
};


// ============ GET /pets ============

export interface ListPetsParams {
  limit?: number;
  offset?: number;
  status?: PetStatus;
  tags?: string[];
}

export const getListPetsQueryKey = (params: ListPetsParams) =>
  ['listPets', params.limit, params.offset, params.status, params.tags] as const;

export type ListPetsQueryKey = ReturnType<typeof getListPetsQueryKey>;

export const getListPetsQueryOptions = <TData = PetList>(
  params: ListPetsParams,
  options?: Partial<UseQueryOptions<PetList, Error, TData>>
) =>
  queryOptions({
    queryKey: getListPetsQueryKey(params),
    queryFn: () => (() => {
      const searchParams = new URLSearchParams();
      if (params.limit !== undefined) searchParams.append('limit', String(params.limit));
      if (params.offset !== undefined) searchParams.append('offset', String(params.offset));
      if (params.status !== undefined) searchParams.append('status', String(params.status));
      if (params.tags !== undefined) searchParams.append('tags', String(params.tags));
      const query = searchParams.toString();
      const url = `/pets${query ? `?${query}` : ''}`;
      return apiClient(url);
    })(),
    ...options,
  });

/**
 * List all pets
 * @path GET /pets
 */
export const useListPets = <TData = PetList>(
  params: ListPetsParams,
  options?: Partial<UseQueryOptions<PetList, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getListPetsQueryOptions(params, options));
};


// ============ POST /pets ============

export interface CreatePetVariables {
  data: CreatePetRequest;
}

/**
 * Create a new pet
 * @path POST /pets
 */
export const useCreatePet = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, Error, CreatePetVariables, TContext>>
): UseMutationResult<Pet, Error, CreatePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient('/pets', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /pets/{petId} ============

export interface GetPetParams {
  petId: string;
}

export const getGetPetQueryKey = (params: GetPetParams) =>
  ['getPet', params.petId] as const;

export type GetPetQueryKey = ReturnType<typeof getGetPetQueryKey>;

export const getGetPetQueryOptions = <TData = Pet>(
  params: GetPetParams,
  options?: Partial<UseQueryOptions<Pet, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetPetQueryKey(params),
    queryFn: () => (() => {
      const url = `/pets/${params.petId}`;
      return apiClient(url);
    })(),
    ...options,
  });

/**
 * Get a pet by ID
 * @path GET /pets/{petId}
 */
export const useGetPet = <TData = Pet>(
  params: GetPetParams,
  options?: Partial<UseQueryOptions<Pet, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetPetQueryOptions(params, options));
};


// ============ PUT /pets/{petId} ============

export interface UpdatePetVariables {
  petId: string;
  data: UpdatePetRequest;
}

/**
 * Update a pet
 * @path PUT /pets/{petId}
 */
export const useUpdatePet = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, Error, UpdatePetVariables, TContext>>
): UseMutationResult<Pet, Error, UpdatePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient(`/pets/${vars.petId}`, { method: 'PUT', body: vars.data }),
    ...options,
  });
};


// ============ PATCH /pets/{petId} ============

export interface PatchPetVariables {
  petId: string;
  data: PatchPetRequest;
}

/**
 * Partially update a pet
 * @path PATCH /pets/{petId}
 */
export const usePatchPet = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, Error, PatchPetVariables, TContext>>
): UseMutationResult<Pet, Error, PatchPetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient(`/pets/${vars.petId}`, { method: 'PATCH', body: vars.data }),
    ...options,
  });
};


// ============ DELETE /pets/{petId} ============

export interface DeletePetVariables {
  petId: string;
}

/**
 * Delete a pet
 * @path DELETE /pets/{petId}
 */
export const useDeletePet = <TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, Error, DeletePetVariables, TContext>>
): UseMutationResult<unknown, Error, DeletePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient(`/pets/${vars.petId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ POST /pets/{petId}/photo ============

export interface UploadPetPhotoVariables {
  petId: string;
  data: PhotoUploadRequest;
}

/**
 * Upload a pet photo
 * @path POST /pets/{petId}/photo
 */
export const useUploadPetPhoto = <TContext = unknown>(
  options?: Partial<UseMutationOptions<PhotoUploadResponse, Error, UploadPetPhotoVariables, TContext>>
): UseMutationResult<PhotoUploadResponse, Error, UploadPetPhotoVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient(`/pets/${vars.petId}/photo`, { method: 'POST', body: toFormData(vars.data, { path: '/pets/{petId}/photo', method: 'POST' }) }),
    ...options,
  });
};


// ============ POST /pets/search ============

export const getSearchPetsQueryKey = () => ['searchPets'] as const;

export type SearchPetsQueryKey = ReturnType<typeof getSearchPetsQueryKey>;

export const getSearchPetsQueryOptions = <TData = PetList>(
  options?: Partial<UseQueryOptions<PetList, Error, TData>>
) =>
  queryOptions({
    queryKey: getSearchPetsQueryKey(),
    queryFn: () => apiClient('/pets/search'),
    ...options,
  });

/**
 * Search pets with complex criteria
 * @path POST /pets/search
 */
export const useSearchPets = <TData = PetList>(
  options?: Partial<UseQueryOptions<PetList, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getSearchPetsQueryOptions(options));
};


// ============ POST /pets/bulk ============

export interface CreatePetsBulkVariables {
  data: CreatePetRequest[];
}

/**
 * Create multiple pets
 * @path POST /pets/bulk
 */
export const useCreatePetsBulk = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet[], Error, CreatePetsBulkVariables, TContext>>
): UseMutationResult<Pet[], Error, CreatePetsBulkVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient('/pets/bulk', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /users ============

export interface ListUsersParams {
  role?: UserRole;
}

export const getListUsersQueryKey = (params: ListUsersParams) =>
  ['listUsers', params.role] as const;

export type ListUsersQueryKey = ReturnType<typeof getListUsersQueryKey>;

export const getListUsersQueryOptions = <TData = User[]>(
  params: ListUsersParams,
  options?: Partial<UseQueryOptions<User[], Error, TData>>
) =>
  queryOptions({
    queryKey: getListUsersQueryKey(params),
    queryFn: () => (() => {
      const searchParams = new URLSearchParams();
      if (params.role !== undefined) searchParams.append('role', String(params.role));
      const query = searchParams.toString();
      const url = `/users${query ? `?${query}` : ''}`;
      return apiClient(url);
    })(),
    ...options,
  });

/**
 * List all users
 * @path GET /users
 */
export const useListUsers = <TData = User[]>(
  params: ListUsersParams,
  options?: Partial<UseQueryOptions<User[], Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getListUsersQueryOptions(params, options));
};


// ============ POST /users ============

export interface CreateUserVariables {
  data: CreateUserRequest;
}

/**
 * Create a new user
 * @path POST /users
 */
export const useCreateUser = <TContext = unknown>(
  options?: Partial<UseMutationOptions<User, Error, CreateUserVariables, TContext>>
): UseMutationResult<User, Error, CreateUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient('/users', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /users/{userId} ============

export interface GetUserParams {
  userId: number;
}

export const getGetUserQueryKey = (params: GetUserParams) =>
  ['getUser', params.userId] as const;

export type GetUserQueryKey = ReturnType<typeof getGetUserQueryKey>;

export const getGetUserQueryOptions = <TData = User>(
  params: GetUserParams,
  options?: Partial<UseQueryOptions<User, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetUserQueryKey(params),
    queryFn: () => (() => {
      const url = `/users/${params.userId}`;
      return apiClient(url);
    })(),
    ...options,
  });

/**
 * Get a user by ID
 * @path GET /users/{userId}
 */
export const useGetUser = <TData = User>(
  params: GetUserParams,
  options?: Partial<UseQueryOptions<User, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetUserQueryOptions(params, options));
};


// ============ DELETE /users/{userId} ============

export interface DeleteUserVariables {
  userId: number;
}

/**
 * Delete a user
 * @path DELETE /users/{userId}
 */
export const useDeleteUser = <TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, Error, DeleteUserVariables, TContext>>
): UseMutationResult<unknown, Error, DeleteUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient(`/users/${vars.userId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ GET /users/{userId}/pets ============

export interface GetUserPetsParams {
  userId: number;
  status?: PetStatus;
}

export const getGetUserPetsQueryKey = (params: GetUserPetsParams) =>
  ['getUserPets', params.userId, params.status] as const;

export type GetUserPetsQueryKey = ReturnType<typeof getGetUserPetsQueryKey>;

export const getGetUserPetsQueryOptions = <TData = Pet[]>(
  params: GetUserPetsParams,
  options?: Partial<UseQueryOptions<Pet[], Error, TData>>
) =>
  queryOptions({
    queryKey: getGetUserPetsQueryKey(params),
    queryFn: () => (() => {
      const searchParams = new URLSearchParams();
      if (params.status !== undefined) searchParams.append('status', String(params.status));
      const query = searchParams.toString();
      const url = `/users/${params.userId}/pets${query ? `?${query}` : ''}`;
      return apiClient(url);
    })(),
    ...options,
  });

/**
 * Get pets owned by a user
 * @path GET /users/{userId}/pets
 */
export const useGetUserPets = <TData = Pet[]>(
  params: GetUserPetsParams,
  options?: Partial<UseQueryOptions<Pet[], Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetUserPetsQueryOptions(params, options));
};


// ============ POST /files/upload ============

export interface UploadFileVariables {
  data: FileUploadRequest;
}

/**
 * Upload a file
 * @path POST /files/upload
 */
export const useUploadFile = <TContext = unknown>(
  options?: Partial<UseMutationOptions<FileUploadResponse, Error, UploadFileVariables, TContext>>
): UseMutationResult<FileUploadResponse, Error, UploadFileVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient('/files/upload', { method: 'POST', body: toFormData(vars.data, { path: '/files/upload', method: 'POST' }) }),
    ...options,
  });
};


// ============ GET /files/{fileId} ============

export interface GetFileParams {
  fileId: string;
}

export const getGetFileQueryKey = (params: GetFileParams) =>
  ['getFile', params.fileId] as const;

export type GetFileQueryKey = ReturnType<typeof getGetFileQueryKey>;

export const getGetFileQueryOptions = <TData = FileMetadata>(
  params: GetFileParams,
  options?: Partial<UseQueryOptions<FileMetadata, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetFileQueryKey(params),
    queryFn: () => (() => {
      const url = `/files/${params.fileId}`;
      return apiClient(url);
    })(),
    ...options,
  });

/**
 * Get file metadata
 * @path GET /files/{fileId}
 */
export const useGetFile = <TData = FileMetadata>(
  params: GetFileParams,
  options?: Partial<UseQueryOptions<FileMetadata, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetFileQueryOptions(params, options));
};


// ============ DELETE /files/{fileId} ============

export interface DeleteFileVariables {
  fileId: string;
}

/**
 * Delete a file
 * @path DELETE /files/{fileId}
 */
export const useDeleteFile = <TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, Error, DeleteFileVariables, TContext>>
): UseMutationResult<unknown, Error, DeleteFileVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient(`/files/${vars.fileId}`, { method: 'DELETE' }),
    ...options,
  });
};
