// Generated by schema-gen - DO NOT EDIT

import { useQuery, queryOptions, useMutation } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';
import { apiClient } from '../lib/client';
import type { ApiResponse, Order, Pet, User } from './types';


// ============ POST /pet ============

export interface AddPetVariables {
  data: Pet;
}

/**
 * Add a new pet to the store.
 * @path POST /pet
 */
export const useAddPet = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, Error, AddPetVariables, TContext>>
): UseMutationResult<Pet, Error, AddPetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>('/pet', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ PUT /pet ============

export interface UpdatePetVariables {
  data: Pet;
}

/**
 * Update an existing pet.
 * @path PUT /pet
 */
export const useUpdatePet = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, Error, UpdatePetVariables, TContext>>
): UseMutationResult<Pet, Error, UpdatePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>('/pet', { method: 'PUT', body: vars.data }),
    ...options,
  });
};


// ============ GET /pet/findByStatus ============

export interface FindPetsByStatusParams {
  status: string;
}

export const getFindPetsByStatusQueryKey = (params: FindPetsByStatusParams) =>
  ['findPetsByStatus', params.status] as const;

export type FindPetsByStatusQueryKey = ReturnType<typeof getFindPetsByStatusQueryKey>;

export const getFindPetsByStatusQueryOptions = <TData = Pet[]>(
  params: FindPetsByStatusParams,
  options?: Partial<UseQueryOptions<Pet[], Error, TData>>
) =>
  queryOptions({
    queryKey: getFindPetsByStatusQueryKey(params),
    queryFn: () => (() => {
      const searchParams = new URLSearchParams();
      if (params.status !== undefined) searchParams.append('status', String(params.status));
      const query = searchParams.toString();
      const url = `/pet/findByStatus${query ? `?${query}` : ''}`;
      return apiClient<Pet[]>(url);
    })(),
    ...options,
  });

/**
 * Finds Pets by status.
 * @path GET /pet/findByStatus
 */
export const useFindPetsByStatus = <TData = Pet[]>(
  params: FindPetsByStatusParams,
  options?: Partial<UseQueryOptions<Pet[], Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getFindPetsByStatusQueryOptions(params, options));
};


// ============ GET /pet/findByTags ============

export interface FindPetsByTagsParams {
  tags: string[];
}

export const getFindPetsByTagsQueryKey = (params: FindPetsByTagsParams) =>
  ['findPetsByTags', params.tags] as const;

export type FindPetsByTagsQueryKey = ReturnType<typeof getFindPetsByTagsQueryKey>;

export const getFindPetsByTagsQueryOptions = <TData = Pet[]>(
  params: FindPetsByTagsParams,
  options?: Partial<UseQueryOptions<Pet[], Error, TData>>
) =>
  queryOptions({
    queryKey: getFindPetsByTagsQueryKey(params),
    queryFn: () => (() => {
      const searchParams = new URLSearchParams();
      if (params.tags !== undefined) searchParams.append('tags', String(params.tags));
      const query = searchParams.toString();
      const url = `/pet/findByTags${query ? `?${query}` : ''}`;
      return apiClient<Pet[]>(url);
    })(),
    ...options,
  });

/**
 * Finds Pets by tags.
 * @path GET /pet/findByTags
 */
export const useFindPetsByTags = <TData = Pet[]>(
  params: FindPetsByTagsParams,
  options?: Partial<UseQueryOptions<Pet[], Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getFindPetsByTagsQueryOptions(params, options));
};


// ============ GET /pet/{petId} ============

export interface GetPetByIdParams {
  petId: number;
}

export const getGetPetByIdQueryKey = (params: GetPetByIdParams) =>
  ['getPetById', params.petId] as const;

export type GetPetByIdQueryKey = ReturnType<typeof getGetPetByIdQueryKey>;

export const getGetPetByIdQueryOptions = <TData = Pet>(
  params: GetPetByIdParams,
  options?: Partial<UseQueryOptions<Pet, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetPetByIdQueryKey(params),
    queryFn: () => (() => {
      const url = `/pet/${params.petId}`;
      return apiClient<Pet>(url);
    })(),
    ...options,
  });

/**
 * Find pet by ID.
 * @path GET /pet/{petId}
 */
export const useGetPetById = <TData = Pet>(
  params: GetPetByIdParams,
  options?: Partial<UseQueryOptions<Pet, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetPetByIdQueryOptions(params, options));
};


// ============ POST /pet/{petId} ============

export interface UpdatePetWithFormVariables {
  petId: number;
}

/**
 * Updates a pet in the store with form data.
 * @path POST /pet/{petId}
 */
export const useUpdatePetWithForm = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, Error, UpdatePetWithFormVariables, TContext>>
): UseMutationResult<Pet, Error, UpdatePetWithFormVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>(`/pet/${vars.petId}`, { method: 'POST' }),
    ...options,
  });
};


// ============ DELETE /pet/{petId} ============

export interface DeletePetVariables {
  petId: number;
}

/**
 * Deletes a pet.
 * @path DELETE /pet/{petId}
 */
export const useDeletePet = <TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, Error, DeletePetVariables, TContext>>
): UseMutationResult<unknown, Error, DeletePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/pet/${vars.petId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ POST /pet/{petId}/uploadImage ============

export interface UploadFileVariables {
  petId: number;
  data: unknown;
}

/**
 * Uploads an image.
 * @path POST /pet/{petId}/uploadImage
 */
export const useUploadFile = <TContext = unknown>(
  options?: Partial<UseMutationOptions<ApiResponse, Error, UploadFileVariables, TContext>>
): UseMutationResult<ApiResponse, Error, UploadFileVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<ApiResponse>(`/pet/${vars.petId}/uploadImage`, { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /store/inventory ============

export const getGetInventoryQueryKey = () => ['getInventory'] as const;

export type GetInventoryQueryKey = ReturnType<typeof getGetInventoryQueryKey>;

export const getGetInventoryQueryOptions = <TData = unknown>(
  options?: Partial<UseQueryOptions<unknown, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetInventoryQueryKey(),
    queryFn: () => apiClient<unknown>('/store/inventory'),
    ...options,
  });

/**
 * Returns pet inventories by status.
 * @path GET /store/inventory
 */
export const useGetInventory = <TData = unknown>(
  options?: Partial<UseQueryOptions<unknown, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetInventoryQueryOptions(options));
};


// ============ POST /store/order ============

export interface PlaceOrderVariables {
  data: Order;
}

/**
 * Place an order for a pet.
 * @path POST /store/order
 */
export const usePlaceOrder = <TContext = unknown>(
  options?: Partial<UseMutationOptions<Order, Error, PlaceOrderVariables, TContext>>
): UseMutationResult<Order, Error, PlaceOrderVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Order>('/store/order', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /store/order/{orderId} ============

export interface GetOrderByIdParams {
  orderId: number;
}

export const getGetOrderByIdQueryKey = (params: GetOrderByIdParams) =>
  ['getOrderById', params.orderId] as const;

export type GetOrderByIdQueryKey = ReturnType<typeof getGetOrderByIdQueryKey>;

export const getGetOrderByIdQueryOptions = <TData = Order>(
  params: GetOrderByIdParams,
  options?: Partial<UseQueryOptions<Order, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetOrderByIdQueryKey(params),
    queryFn: () => (() => {
      const url = `/store/order/${params.orderId}`;
      return apiClient<Order>(url);
    })(),
    ...options,
  });

/**
 * Find purchase order by ID.
 * @path GET /store/order/{orderId}
 */
export const useGetOrderById = <TData = Order>(
  params: GetOrderByIdParams,
  options?: Partial<UseQueryOptions<Order, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetOrderByIdQueryOptions(params, options));
};


// ============ DELETE /store/order/{orderId} ============

export interface DeleteOrderVariables {
  orderId: number;
}

/**
 * Delete purchase order by identifier.
 * @path DELETE /store/order/{orderId}
 */
export const useDeleteOrder = <TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, Error, DeleteOrderVariables, TContext>>
): UseMutationResult<unknown, Error, DeleteOrderVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/store/order/${vars.orderId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ POST /user ============

export interface CreateUserVariables {
  data: User;
}

/**
 * Create user.
 * @path POST /user
 */
export const useCreateUser = <TContext = unknown>(
  options?: Partial<UseMutationOptions<User, Error, CreateUserVariables, TContext>>
): UseMutationResult<User, Error, CreateUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<User>('/user', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ POST /user/createWithList ============

export interface CreateUsersWithListInputVariables {
  data: User[];
}

/**
 * Creates list of users with given input array.
 * @path POST /user/createWithList
 */
export const useCreateUsersWithListInput = <TContext = unknown>(
  options?: Partial<UseMutationOptions<User, Error, CreateUsersWithListInputVariables, TContext>>
): UseMutationResult<User, Error, CreateUsersWithListInputVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<User>('/user/createWithList', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /user/login ============

export interface LoginUserParams {
  username?: string;
  password?: string;
}

export const getLoginUserQueryKey = (params: LoginUserParams) =>
  ['loginUser', params.username, params.password] as const;

export type LoginUserQueryKey = ReturnType<typeof getLoginUserQueryKey>;

export const getLoginUserQueryOptions = <TData = string>(
  params: LoginUserParams,
  options?: Partial<UseQueryOptions<string, Error, TData>>
) =>
  queryOptions({
    queryKey: getLoginUserQueryKey(params),
    queryFn: () => (() => {
      const searchParams = new URLSearchParams();
      if (params.username !== undefined) searchParams.append('username', String(params.username));
      if (params.password !== undefined) searchParams.append('password', String(params.password));
      const query = searchParams.toString();
      const url = `/user/login${query ? `?${query}` : ''}`;
      return apiClient<string>(url);
    })(),
    ...options,
  });

/**
 * Logs user into the system.
 * @path GET /user/login
 */
export const useLoginUser = <TData = string>(
  params: LoginUserParams,
  options?: Partial<UseQueryOptions<string, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getLoginUserQueryOptions(params, options));
};


// ============ GET /user/logout ============

export const getLogoutUserQueryKey = () => ['logoutUser'] as const;

export type LogoutUserQueryKey = ReturnType<typeof getLogoutUserQueryKey>;

export const getLogoutUserQueryOptions = <TData = unknown>(
  options?: Partial<UseQueryOptions<unknown, Error, TData>>
) =>
  queryOptions({
    queryKey: getLogoutUserQueryKey(),
    queryFn: () => apiClient<unknown>('/user/logout'),
    ...options,
  });

/**
 * Logs out current logged in user session.
 * @path GET /user/logout
 */
export const useLogoutUser = <TData = unknown>(
  options?: Partial<UseQueryOptions<unknown, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getLogoutUserQueryOptions(options));
};


// ============ GET /user/{username} ============

export interface GetUserByNameParams {
  username: string;
}

export const getGetUserByNameQueryKey = (params: GetUserByNameParams) =>
  ['getUserByName', params.username] as const;

export type GetUserByNameQueryKey = ReturnType<typeof getGetUserByNameQueryKey>;

export const getGetUserByNameQueryOptions = <TData = User>(
  params: GetUserByNameParams,
  options?: Partial<UseQueryOptions<User, Error, TData>>
) =>
  queryOptions({
    queryKey: getGetUserByNameQueryKey(params),
    queryFn: () => (() => {
      const url = `/user/${params.username}`;
      return apiClient<User>(url);
    })(),
    ...options,
  });

/**
 * Get user by user name.
 * @path GET /user/{username}
 */
export const useGetUserByName = <TData = User>(
  params: GetUserByNameParams,
  options?: Partial<UseQueryOptions<User, Error, TData>>
): UseQueryResult<TData, Error> => {
  return useQuery(getGetUserByNameQueryOptions(params, options));
};


// ============ PUT /user/{username} ============

export interface UpdateUserVariables {
  username: string;
  data: User;
}

/**
 * Update user resource.
 * @path PUT /user/{username}
 */
export const useUpdateUser = <TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, Error, UpdateUserVariables, TContext>>
): UseMutationResult<unknown, Error, UpdateUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/user/${vars.username}`, { method: 'PUT', body: vars.data }),
    ...options,
  });
};


// ============ DELETE /user/{username} ============

export interface DeleteUserVariables {
  username: string;
}

/**
 * Delete user resource.
 * @path DELETE /user/{username}
 */
export const useDeleteUser = <TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, Error, DeleteUserVariables, TContext>>
): UseMutationResult<unknown, Error, DeleteUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/user/${vars.username}`, { method: 'DELETE' }),
    ...options,
  });
};
