// Generated by schema-gen - DO NOT EDIT

/**
 * Add a new pet to the store.
 * @path POST /pet
 */
export const addPetPath = () => '/pet' as const;

/**
 * Update an existing pet.
 * @path PUT /pet
 */
export const updatePetPath = () => '/pet' as const;

/**
 * Finds Pets by status.
 * @path GET /pet/findByStatus
 */
export const findPetsByStatusPath = () => '/pet/findByStatus' as const;

/**
 * Finds Pets by tags.
 * @path GET /pet/findByTags
 */
export const findPetsByTagsPath = () => '/pet/findByTags' as const;

/**
 * Find pet by ID.
 * @path GET /pet/{petId}
 */
export const getPetByIdPath = (params: { petId: number }) => `/pet/${params.petId}` as const;

/**
 * Updates a pet in the store with form data.
 * @path POST /pet/{petId}
 */
export const updatePetWithFormPath = (params: { petId: number }) => `/pet/${params.petId}` as const;

/**
 * Deletes a pet.
 * @path DELETE /pet/{petId}
 */
export const deletePetPath = (params: { petId: number }) => `/pet/${params.petId}` as const;

/**
 * Uploads an image.
 * @path POST /pet/{petId}/uploadImage
 */
export const uploadFilePath = (params: { petId: number }) => `/pet/${params.petId}/uploadImage` as const;

/**
 * Returns pet inventories by status.
 * @path GET /store/inventory
 */
export const getInventoryPath = () => '/store/inventory' as const;

/**
 * Place an order for a pet.
 * @path POST /store/order
 */
export const placeOrderPath = () => '/store/order' as const;

/**
 * Find purchase order by ID.
 * @path GET /store/order/{orderId}
 */
export const getOrderByIdPath = (params: { orderId: number }) => `/store/order/${params.orderId}` as const;

/**
 * Delete purchase order by identifier.
 * @path DELETE /store/order/{orderId}
 */
export const deleteOrderPath = (params: { orderId: number }) => `/store/order/${params.orderId}` as const;

/**
 * Create user.
 * @path POST /user
 */
export const createUserPath = () => '/user' as const;

/**
 * Creates list of users with given input array.
 * @path POST /user/createWithList
 */
export const createUsersWithListInputPath = () => '/user/createWithList' as const;

/**
 * Logs user into the system.
 * @path GET /user/login
 */
export const loginUserPath = () => '/user/login' as const;

/**
 * Logs out current logged in user session.
 * @path GET /user/logout
 */
export const logoutUserPath = () => '/user/logout' as const;

/**
 * Get user by user name.
 * @path GET /user/{username}
 */
export const getUserByNamePath = (params: { username: string }) => `/user/${params.username}` as const;

/**
 * Update user resource.
 * @path PUT /user/{username}
 */
export const updateUserPath = (params: { username: string }) => `/user/${params.username}` as const;

/**
 * Delete user resource.
 * @path DELETE /user/{username}
 */
export const deleteUserPath = (params: { username: string }) => `/user/${params.username}` as const;
