// Generated by schema-gen - DO NOT EDIT

export interface CreatePetRequest {
  name: string;
  species?: string;
  breed?: string;
  age?: number;
  status?: PetStatus;
  tags?: string[];
  ownerId?: number;
}

export interface CreateUserRequest {
  email: string;
  password: string;
  name?: string;
  role?: UserRole;
}

export interface Error {
  code: string;
  message: string;
  details?: unknown;
}

export interface FileMetadata {
  id: string;
  filename: string;
  size: number;
  contentType: string;
  uploadedAt?: string;
  metadata?: unknown;
}

export interface FileUploadRequest {
  file: string;
  filename?: string;
  contentType?: string;
  metadata?: unknown;
}

export interface FileUploadResponse {
  id: string;
  url: string;
  size?: number;
  contentType?: string;
}

export interface HealthStatus {
  status: HealthStatus_Status;
  timestamp: string;
  version?: string;
  uptime?: number;
}

export interface PatchPetRequest {
  name?: string;
  species?: string;
  breed?: string;
  age?: number;
  status?: PetStatus;
  tags?: string[];
}

export interface Pet {
  id: string;
  name: string;
  species?: string;
  breed?: string;
  age?: number;
  status: PetStatus;
  tags?: string[];
  owner?: User;
  photoUrl?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface PetList {
  items: Pet[];
  total: number;
  limit?: number;
  offset?: number;
  hasMore?: boolean;
}

export interface PetSearchCriteria {
  query?: string;
  species?: string[];
  status?: PetStatus[];
  ageRange?: unknown;
  tags?: string[];
}

export interface PhotoUploadRequest {
  file: string;
  caption?: string;
}

export interface PhotoUploadResponse {
  id: string;
  url: string;
  thumbnailUrl?: string;
}

export interface UpdatePetRequest {
  name: string;
  species?: string;
  breed?: string;
  age?: number;
  status: PetStatus;
  tags?: string[];
}

export interface User {
  id: number;
  email: string;
  name?: string;
  role: UserRole;
  avatar?: string;
  createdAt?: string;
}

export interface ValidationError {
  code: string;
  message: string;
  errors: unknown[];
}

