//! TypeScript code generation

use crate::ast::{
    EnumNode, EnumValue, EnumValueType, PrimitiveType, PropertyNode, SchemaAst, TypeKind,
    TypeNode, TypeRef,
};
use crate::error::Result;
use serde::{Deserialize, Serialize};

use super::{GeneratedFile, Generator};

/// TypeScript generation options
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TypeScriptOptions {
    /// Use `interface` instead of `type` for objects
    #[serde(default)]
    pub prefer_interfaces: bool,

    /// Add `readonly` modifier to all properties
    #[serde(default)]
    pub readonly_properties: bool,

    /// Generate JSDoc comments from descriptions
    #[serde(default = "default_true")]
    pub generate_jsdoc: bool,

    /// Export style: "named" or "default"
    #[serde(default)]
    pub export_style: ExportStyle,

    /// Enum style: "enum", "const-enum", or "union"
    #[serde(default)]
    pub enum_style: EnumStyle,
}

fn default_true() -> bool {
    true
}

/// Export style for generated code
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ExportStyle {
    #[default]
    Named,
    Default,
}

/// Enum generation style
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EnumStyle {
    #[default]
    Enum,
    ConstEnum,
    Union,
}

/// TypeScript code generator
pub struct TypeScriptGenerator {
    options: TypeScriptOptions,
}

impl TypeScriptGenerator {
    /// Create a new generator with options
    pub fn new(options: TypeScriptOptions) -> Self {
        Self { options }
    }

    /// Generate enum definitions only
    pub fn generate_enums(&self, ast: &SchemaAst) -> Result<Vec<GeneratedFile>> {
        let mut output = String::new();
        output.push_str("// Generated by schema-gen - DO NOT EDIT\n\n");

        for enum_node in ast.enums.values() {
            output.push_str(&self.generate_enum(enum_node));
            output.push_str("\n\n");
        }

        Ok(vec![GeneratedFile {
            path: "enums.ts".to_string(),
            content: output,
            skip_format: false,
        }])
    }

    /// Generate constants only
    pub fn generate_constants(&self, ast: &SchemaAst) -> Result<Vec<GeneratedFile>> {
        let mut output = String::new();
        output.push_str("// Generated by schema-gen - DO NOT EDIT\n\n");

        // Generate endpoint paths
        output.push_str("export const endpoints = {\n");
        for endpoint in &ast.endpoints {
            let name = endpoint
                .operation_id
                .as_ref()
                .unwrap_or(&endpoint.id)
                .clone();
            output.push_str(&format!("  {}: '{}',\n", name, endpoint.path));
        }
        output.push_str("} as const;\n\n");

        // Generate HTTP methods
        output.push_str("export const methods = {\n");
        for endpoint in &ast.endpoints {
            let name = endpoint
                .operation_id
                .as_ref()
                .unwrap_or(&endpoint.id)
                .clone();
            output.push_str(&format!(
                "  {}: '{}',\n",
                name,
                endpoint.method.as_str().to_uppercase()
            ));
        }
        output.push_str("} as const;\n");

        Ok(vec![GeneratedFile {
            path: "constants.ts".to_string(),
            content: output,
            skip_format: false,
        }])
    }

    /// Generate a single enum
    fn generate_enum(&self, enum_node: &EnumNode) -> String {
        let mut output = String::new();

        // JSDoc comment
        if self.options.generate_jsdoc {
            if let Some(desc) = &enum_node.description {
                output.push_str(&format!("/** {} */\n", desc));
            }
        }

        match self.options.enum_style {
            EnumStyle::Enum | EnumStyle::ConstEnum => {
                let const_prefix = if self.options.enum_style == EnumStyle::ConstEnum {
                    "const "
                } else {
                    ""
                };

                output.push_str(&format!("export {}enum {} {{\n", const_prefix, enum_node.name));

                for variant in &enum_node.variants {
                    let value = match &variant.value {
                        EnumValue::String(s) => format!("'{}'", s),
                        EnumValue::Integer(i) => i.to_string(),
                    };
                    output.push_str(&format!("  {} = {},\n", variant.name, value));
                }

                output.push_str("}");
            }
            EnumStyle::Union => {
                // Generate as union type
                let variants: Vec<String> = enum_node
                    .variants
                    .iter()
                    .map(|v| match &v.value {
                        EnumValue::String(s) => format!("'{}'", s),
                        EnumValue::Integer(i) => i.to_string(),
                    })
                    .collect();

                output.push_str(&format!(
                    "export type {} = {};",
                    enum_node.name,
                    variants.join(" | ")
                ));

                // Also generate a values object
                output.push_str(&format!(
                    "\n\nexport const {}Values = {{\n",
                    enum_node.name
                ));
                for variant in &enum_node.variants {
                    let value = match &variant.value {
                        EnumValue::String(s) => format!("'{}'", s),
                        EnumValue::Integer(i) => i.to_string(),
                    };
                    output.push_str(&format!("  {}: {},\n", variant.name, value));
                }
                output.push_str("} as const;");
            }
        }

        output
    }

    /// Generate a single type
    fn generate_type(&self, type_node: &TypeNode) -> String {
        let mut output = String::new();

        // JSDoc comment
        if self.options.generate_jsdoc {
            if let Some(desc) = &type_node.description {
                output.push_str(&format!("/** {} */\n", desc));
            }
            if type_node.deprecated {
                output.push_str("/** @deprecated */\n");
            }
        }

        match &type_node.kind {
            TypeKind::Object { properties, .. } if self.options.prefer_interfaces => {
                output.push_str(&format!("export interface {} {{\n", type_node.name));
                for prop in properties {
                    output.push_str(&self.generate_property(prop));
                }
                output.push_str("}");
            }
            _ => {
                output.push_str(&format!(
                    "export type {} = {};",
                    type_node.name,
                    self.type_kind_to_string(&type_node.kind)
                ));
            }
        }

        output
    }

    /// Generate a property
    fn generate_property(&self, prop: &PropertyNode) -> String {
        let mut output = String::new();

        // JSDoc for property
        if self.options.generate_jsdoc {
            if let Some(desc) = &prop.description {
                output.push_str(&format!("  /** {} */\n", desc));
            }
        }

        let readonly = if self.options.readonly_properties || prop.readonly {
            "readonly "
        } else {
            ""
        };

        let optional = if !prop.required { "?" } else { "" };
        let type_str = self.type_ref_to_string(&prop.type_ref);

        output.push_str(&format!(
            "  {}{}{}: {};\n",
            readonly, prop.name, optional, type_str
        ));

        output
    }

    /// Convert TypeKind to TypeScript string
    fn type_kind_to_string(&self, kind: &TypeKind) -> String {
        match kind {
            TypeKind::Object { properties, .. } => {
                let props: Vec<String> = properties
                    .iter()
                    .map(|p| {
                        let optional = if !p.required { "?" } else { "" };
                        format!("{}{}: {}", p.name, optional, self.type_ref_to_string(&p.type_ref))
                    })
                    .collect();
                format!("{{ {} }}", props.join("; "))
            }
            TypeKind::Array { items } => {
                format!("{}[]", self.type_ref_to_string(items))
            }
            TypeKind::Union { variants, .. } => {
                let types: Vec<String> = variants
                    .iter()
                    .map(|v| self.type_ref_to_string(v))
                    .collect();
                types.join(" | ")
            }
            TypeKind::Intersection { parts } => {
                let types: Vec<String> = parts
                    .iter()
                    .map(|p| self.type_ref_to_string(p))
                    .collect();
                types.join(" & ")
            }
            TypeKind::Primitive(p) => self.primitive_to_string(p),
            TypeKind::Reference { target } => target.clone(),
        }
    }

    /// Convert TypeRef to TypeScript string
    fn type_ref_to_string(&self, type_ref: &TypeRef) -> String {
        match type_ref {
            TypeRef::Named { name, .. } => name.clone(),
            TypeRef::Inline(node) => self.type_kind_to_string(&node.kind),
            TypeRef::Array { items } => format!("{}[]", self.type_ref_to_string(items)),
            TypeRef::Primitive(p) => self.primitive_to_string(p),
            TypeRef::Enum { name, .. } => name.clone(),
            TypeRef::Unknown => "unknown".to_string(),
        }
    }

    /// Convert PrimitiveType to TypeScript string
    fn primitive_to_string(&self, prim: &PrimitiveType) -> String {
        match prim {
            PrimitiveType::String { format, .. } => {
                // Map common formats
                match format.as_deref() {
                    Some("date-time") | Some("date") => "string".to_string(), // Could be Date
                    _ => "string".to_string(),
                }
            }
            PrimitiveType::Number { .. } => "number".to_string(),
            PrimitiveType::Integer { format, .. } => {
                match format.as_deref() {
                    Some("int64") => "bigint".to_string(), // Could be configured
                    _ => "number".to_string(),
                }
            }
            PrimitiveType::Boolean => "boolean".to_string(),
            PrimitiveType::Null => "null".to_string(),
            PrimitiveType::Any => "unknown".to_string(),
        }
    }
}

impl Generator for TypeScriptGenerator {
    fn generate(&self, ast: &SchemaAst) -> Result<Vec<GeneratedFile>> {
        let mut output = String::new();
        output.push_str("// Generated by schema-gen - DO NOT EDIT\n\n");

        // Generate types
        for type_node in ast.types.values() {
            output.push_str(&self.generate_type(type_node));
            output.push_str("\n\n");
        }

        Ok(vec![GeneratedFile {
            path: "types.ts".to_string(),
            content: output,
            skip_format: false,
        }])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ApiInfo, EnumVariant};

    #[test]
    fn test_generate_enum() {
        let gen = TypeScriptGenerator::new(TypeScriptOptions::default());

        let enum_node = EnumNode {
            id: "Status".to_string(),
            name: "Status".to_string(),
            original_name: "Status".to_string(),
            description: Some("User status".to_string()),
            variants: vec![
                EnumVariant {
                    name: "ACTIVE".to_string(),
                    value: EnumValue::String("active".to_string()),
                    description: None,
                },
                EnumVariant {
                    name: "INACTIVE".to_string(),
                    value: EnumValue::String("inactive".to_string()),
                    description: None,
                },
            ],
            value_type: EnumValueType::String,
            source_path: None,
        };

        let output = gen.generate_enum(&enum_node);
        assert!(output.contains("export enum Status"));
        assert!(output.contains("ACTIVE = 'active'"));
    }

    #[test]
    fn test_generate_union_enum() {
        let gen = TypeScriptGenerator::new(TypeScriptOptions {
            enum_style: EnumStyle::Union,
            ..Default::default()
        });

        let enum_node = EnumNode {
            id: "Status".to_string(),
            name: "Status".to_string(),
            original_name: "Status".to_string(),
            description: None,
            variants: vec![
                EnumVariant {
                    name: "ACTIVE".to_string(),
                    value: EnumValue::String("active".to_string()),
                    description: None,
                },
                EnumVariant {
                    name: "INACTIVE".to_string(),
                    value: EnumValue::String("inactive".to_string()),
                    description: None,
                },
            ],
            value_type: EnumValueType::String,
            source_path: None,
        };

        let output = gen.generate_enum(&enum_node);
        assert!(output.contains("export type Status = 'active' | 'inactive'"));
    }
}
