//! TypeScript code generation

use crate::ast::{
    EnumNode, EnumValue, EnumValueType, PrimitiveType, PropertyNode, SchemaAst, TypeKind,
    TypeNode, TypeRef,
};
use crate::error::Result;
use serde::{Deserialize, Serialize};

use super::{GeneratedFile, Generator};

/// TypeScript generation options
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TypeScriptOptions {
    /// Use `interface` instead of `type` for objects
    #[serde(default)]
    pub prefer_interfaces: bool,

    /// Add `readonly` modifier to all properties
    #[serde(default)]
    pub readonly_properties: bool,

    /// Generate JSDoc comments from descriptions
    #[serde(default = "default_true")]
    pub generate_jsdoc: bool,

    /// Export style: "named" or "default"
    #[serde(default)]
    pub export_style: ExportStyle,

    /// Enum style: "enum", "const-enum", or "union"
    #[serde(default)]
    pub enum_style: EnumStyle,

    /// Import path for enums (if separate from types).
    /// When set, generates `import type { ... } from '<path>'` for referenced enums.
    #[serde(default)]
    pub enums_import_path: Option<String>,
}

fn default_true() -> bool {
    true
}

/// Export style for generated code
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ExportStyle {
    #[default]
    Named,
    Default,
}

/// Enum generation style
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EnumStyle {
    #[default]
    Enum,
    ConstEnum,
    Union,
}

use std::collections::HashSet;

/// Context for tracking type references during generation
#[derive(Default)]
struct GenerationContext {
    /// Enum names that have been referenced
    referenced_enums: HashSet<String>,
    /// Type names that have been referenced
    referenced_types: HashSet<String>,
    /// Known enum names in the AST (for distinguishing enums from types)
    known_enums: HashSet<String>,
}

/// TypeScript code generator
pub struct TypeScriptGenerator {
    options: TypeScriptOptions,
}

impl TypeScriptGenerator {
    /// Create a new generator with options
    pub fn new(options: TypeScriptOptions) -> Self {
        Self { options }
    }

    /// Generate enum definitions only
    pub fn generate_enums(&self, ast: &SchemaAst) -> Result<Vec<GeneratedFile>> {
        let mut output = String::new();
        output.push_str("// Generated by schema-gen - DO NOT EDIT\n\n");

        for enum_node in ast.enums.values() {
            output.push_str(&self.generate_enum(enum_node));
            output.push_str("\n\n");
        }

        Ok(vec![GeneratedFile {
            path: "enums.ts".to_string(),
            content: output,
            skip_format: false,
            referenced_enums: Vec::new(),
            referenced_types: Vec::new(),
        }])
    }

    /// Generate constants only
    pub fn generate_constants(&self, ast: &SchemaAst) -> Result<Vec<GeneratedFile>> {
        let mut output = String::new();
        output.push_str("// Generated by schema-gen - DO NOT EDIT\n\n");

        // Generate endpoint paths
        output.push_str("export const endpoints = {\n");
        for endpoint in &ast.endpoints {
            let name = endpoint
                .operation_id
                .as_ref()
                .unwrap_or(&endpoint.id)
                .clone();
            output.push_str(&format!("  {}: '{}',\n", name, endpoint.path));
        }
        output.push_str("} as const;\n\n");

        // Generate HTTP methods
        output.push_str("export const methods = {\n");
        for endpoint in &ast.endpoints {
            let name = endpoint
                .operation_id
                .as_ref()
                .unwrap_or(&endpoint.id)
                .clone();
            output.push_str(&format!(
                "  {}: '{}',\n",
                name,
                endpoint.method.as_str().to_uppercase()
            ));
        }
        output.push_str("} as const;\n");

        Ok(vec![GeneratedFile {
            path: "constants.ts".to_string(),
            content: output,
            skip_format: false,
            referenced_enums: Vec::new(),
            referenced_types: Vec::new(),
        }])
    }

    /// Generate a single enum
    fn generate_enum(&self, enum_node: &EnumNode) -> String {
        let mut output = String::new();

        // JSDoc comment
        if self.options.generate_jsdoc {
            if let Some(desc) = &enum_node.description {
                output.push_str(&format!("/** {} */\n", desc));
            }
        }

        match self.options.enum_style {
            EnumStyle::Enum | EnumStyle::ConstEnum => {
                let const_prefix = if self.options.enum_style == EnumStyle::ConstEnum {
                    "const "
                } else {
                    ""
                };

                output.push_str(&format!("export {}enum {} {{\n", const_prefix, enum_node.name));

                for variant in &enum_node.variants {
                    let value = match &variant.value {
                        EnumValue::String(s) => format!("'{}'", s),
                        EnumValue::Integer(i) => i.to_string(),
                    };
                    output.push_str(&format!("  {} = {},\n", variant.name, value));
                }

                output.push_str("}");
            }
            EnumStyle::Union => {
                // Generate as union type
                let variants: Vec<String> = enum_node
                    .variants
                    .iter()
                    .map(|v| match &v.value {
                        EnumValue::String(s) => format!("'{}'", s),
                        EnumValue::Integer(i) => i.to_string(),
                    })
                    .collect();

                output.push_str(&format!(
                    "export type {} = {};",
                    enum_node.name,
                    variants.join(" | ")
                ));

                // Also generate a values object
                output.push_str(&format!(
                    "\n\nexport const {}Values = {{\n",
                    enum_node.name
                ));
                for variant in &enum_node.variants {
                    let value = match &variant.value {
                        EnumValue::String(s) => format!("'{}'", s),
                        EnumValue::Integer(i) => i.to_string(),
                    };
                    output.push_str(&format!("  {}: {},\n", variant.name, value));
                }
                output.push_str("} as const;");
            }
        }

        output
    }

    /// Generate a single type
    fn generate_type(&self, type_node: &TypeNode) -> String {
        self.generate_type_with_ctx(type_node, None)
    }

    /// Generate a single type with optional context for tracking references
    fn generate_type_with_ctx(
        &self,
        type_node: &TypeNode,
        mut ctx: Option<&mut GenerationContext>,
    ) -> String {
        let mut output = String::new();

        // JSDoc comment
        if self.options.generate_jsdoc {
            if let Some(desc) = &type_node.description {
                output.push_str(&format!("/** {} */\n", desc));
            }
            if type_node.deprecated {
                output.push_str("/** @deprecated */\n");
            }
        }

        match &type_node.kind {
            TypeKind::Object { properties, .. } if self.options.prefer_interfaces => {
                output.push_str(&format!("export interface {} {{\n", type_node.name));
                for prop in properties {
                    output.push_str(&self.generate_property_with_ctx(prop, ctx.as_deref_mut()));
                }
                output.push_str("}");
            }
            _ => {
                output.push_str(&format!(
                    "export type {} = {};",
                    type_node.name,
                    self.type_kind_to_string_with_ctx(&type_node.kind, ctx)
                ));
            }
        }

        output
    }

    /// Generate a property
    fn generate_property(&self, prop: &PropertyNode) -> String {
        self.generate_property_with_ctx(prop, None)
    }

    /// Generate a property with optional context for tracking references
    fn generate_property_with_ctx(
        &self,
        prop: &PropertyNode,
        ctx: Option<&mut GenerationContext>,
    ) -> String {
        let mut output = String::new();

        // JSDoc for property
        if self.options.generate_jsdoc {
            if let Some(desc) = &prop.description {
                output.push_str(&format!("  /** {} */\n", desc));
            }
        }

        let readonly = if self.options.readonly_properties || prop.readonly {
            "readonly "
        } else {
            ""
        };

        let optional = if !prop.required { "?" } else { "" };
        let type_str = self.type_ref_to_string_with_ctx(&prop.type_ref, ctx);

        output.push_str(&format!(
            "  {}{}{}: {};\n",
            readonly, prop.name, optional, type_str
        ));

        output
    }

    /// Convert TypeKind to TypeScript string
    fn type_kind_to_string(&self, kind: &TypeKind) -> String {
        self.type_kind_to_string_with_ctx(kind, None)
    }

    /// Convert TypeKind to TypeScript string with optional context for tracking references
    fn type_kind_to_string_with_ctx(
        &self,
        kind: &TypeKind,
        mut ctx: Option<&mut GenerationContext>,
    ) -> String {
        match kind {
            TypeKind::Object { properties, .. } => {
                let props: Vec<String> = properties
                    .iter()
                    .map(|p| {
                        let optional = if !p.required { "?" } else { "" };
                        // Note: We can't pass ctx here due to borrow checker, but object literals
                        // in type definitions shouldn't need tracking (they're inline)
                        format!("{}{}: {}", p.name, optional, self.type_ref_to_string(&p.type_ref))
                    })
                    .collect();
                format!("{{ {} }}", props.join("; "))
            }
            TypeKind::Array { items } => {
                format!("{}[]", self.type_ref_to_string_with_ctx(items, ctx))
            }
            TypeKind::Union { variants, .. } => {
                let types: Vec<String> = variants
                    .iter()
                    .map(|v| {
                        // We need to reborrow ctx for each variant
                        self.type_ref_to_string_with_ctx(v, ctx.as_deref_mut())
                    })
                    .collect();
                types.join(" | ")
            }
            TypeKind::Intersection { parts } => {
                let types: Vec<String> = parts
                    .iter()
                    .map(|p| self.type_ref_to_string_with_ctx(p, ctx.as_deref_mut()))
                    .collect();
                types.join(" & ")
            }
            TypeKind::Primitive(p) => self.primitive_to_string(p),
            TypeKind::Reference { target } => {
                // References to other types should be tracked
                if let Some(ctx) = ctx {
                    if ctx.known_enums.contains(target) {
                        ctx.referenced_enums.insert(target.clone());
                    } else {
                        ctx.referenced_types.insert(target.clone());
                    }
                }
                target.clone()
            }
        }
    }

    /// Convert TypeRef to TypeScript string
    fn type_ref_to_string(&self, type_ref: &TypeRef) -> String {
        self.type_ref_to_string_with_ctx(type_ref, None)
    }

    /// Convert TypeRef to TypeScript string with optional context for tracking references
    fn type_ref_to_string_with_ctx(
        &self,
        type_ref: &TypeRef,
        ctx: Option<&mut GenerationContext>,
    ) -> String {
        match type_ref {
            TypeRef::Named { name, .. } => {
                if let Some(ctx) = ctx {
                    // Check if this named type is actually an enum
                    if ctx.known_enums.contains(name) {
                        ctx.referenced_enums.insert(name.clone());
                    } else {
                        ctx.referenced_types.insert(name.clone());
                    }
                }
                name.clone()
            }
            TypeRef::Inline(node) => self.type_kind_to_string_with_ctx(&node.kind, ctx),
            TypeRef::Array { items } => {
                format!("{}[]", self.type_ref_to_string_with_ctx(items, ctx))
            }
            TypeRef::Primitive(p) => self.primitive_to_string(p),
            TypeRef::Enum { name, .. } => {
                if let Some(ctx) = ctx {
                    ctx.referenced_enums.insert(name.clone());
                }
                name.clone()
            }
            TypeRef::Unknown => "unknown".to_string(),
        }
    }

    /// Convert PrimitiveType to TypeScript string
    fn primitive_to_string(&self, prim: &PrimitiveType) -> String {
        match prim {
            PrimitiveType::String { format, .. } => {
                // Map common formats
                match format.as_deref() {
                    Some("date-time") | Some("date") => "string".to_string(), // Could be Date
                    _ => "string".to_string(),
                }
            }
            PrimitiveType::Number { .. } => "number".to_string(),
            PrimitiveType::Integer { format, .. } => {
                match format.as_deref() {
                    Some("int64") => "bigint".to_string(), // Could be configured
                    _ => "number".to_string(),
                }
            }
            PrimitiveType::Boolean => "boolean".to_string(),
            PrimitiveType::Null => "null".to_string(),
            PrimitiveType::Any => "unknown".to_string(),
        }
    }
}

impl Generator for TypeScriptGenerator {
    fn generate(&self, ast: &SchemaAst) -> Result<Vec<GeneratedFile>> {
        // Initialize context with known enums from the AST
        let mut ctx = GenerationContext {
            known_enums: ast.enums.keys().cloned().collect(),
            ..Default::default()
        };

        let mut output = String::new();
        output.push_str("// Generated by schema-gen - DO NOT EDIT\n\n");

        // Generate types with reference tracking
        for type_node in ast.types.values() {
            output.push_str(&self.generate_type_with_ctx(type_node, Some(&mut ctx)));
            output.push_str("\n\n");
        }

        // Generate import statement if enumsImportPath is configured and enums are referenced
        let final_content = if let Some(ref import_path) = self.options.enums_import_path {
            if !ctx.referenced_enums.is_empty() {
                let mut sorted_enums: Vec<_> = ctx.referenced_enums.iter().cloned().collect();
                sorted_enums.sort();
                let import_statement = format!(
                    "import type {{ {} }} from '{}';\n\n",
                    sorted_enums.join(", "),
                    import_path
                );
                // Insert import after the header comment
                let header = "// Generated by schema-gen - DO NOT EDIT\n\n";
                format!("{}{}{}", header, import_statement, &output[header.len()..])
            } else {
                output
            }
        } else {
            output
        };

        // Convert HashSets to sorted Vecs for the metadata
        let mut referenced_enums: Vec<_> = ctx.referenced_enums.into_iter().collect();
        referenced_enums.sort();
        let mut referenced_types: Vec<_> = ctx.referenced_types.into_iter().collect();
        referenced_types.sort();

        Ok(vec![GeneratedFile {
            path: "types.ts".to_string(),
            content: final_content,
            skip_format: false,
            referenced_enums,
            referenced_types,
        }])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ApiInfo, EnumVariant};

    #[test]
    fn test_generate_enum() {
        let gen = TypeScriptGenerator::new(TypeScriptOptions::default());

        let enum_node = EnumNode {
            id: "Status".to_string(),
            name: "Status".to_string(),
            original_name: "Status".to_string(),
            description: Some("User status".to_string()),
            variants: vec![
                EnumVariant {
                    name: "ACTIVE".to_string(),
                    value: EnumValue::String("active".to_string()),
                    description: None,
                },
                EnumVariant {
                    name: "INACTIVE".to_string(),
                    value: EnumValue::String("inactive".to_string()),
                    description: None,
                },
            ],
            value_type: EnumValueType::String,
            source_path: None,
            extensions: Default::default(),
        };

        let output = gen.generate_enum(&enum_node);
        assert!(output.contains("export enum Status"));
        assert!(output.contains("ACTIVE = 'active'"));
    }

    #[test]
    fn test_generate_union_enum() {
        let gen = TypeScriptGenerator::new(TypeScriptOptions {
            enum_style: EnumStyle::Union,
            ..Default::default()
        });

        let enum_node = EnumNode {
            id: "Status".to_string(),
            name: "Status".to_string(),
            original_name: "Status".to_string(),
            description: None,
            variants: vec![
                EnumVariant {
                    name: "ACTIVE".to_string(),
                    value: EnumValue::String("active".to_string()),
                    description: None,
                },
                EnumVariant {
                    name: "INACTIVE".to_string(),
                    value: EnumValue::String("inactive".to_string()),
                    description: None,
                },
            ],
            value_type: EnumValueType::String,
            source_path: None,
            extensions: Default::default(),
        };

        let output = gen.generate_enum(&enum_node);
        assert!(output.contains("export type Status = 'active' | 'inactive'"));
    }
}
