// Generated by schema-gen - DO NOT EDIT

export enum Order_Status {
  PLACED = 'placed',
  APPROVED = 'approved',
  DELIVERED = 'delivered',
}

export enum Pet_Status {
  AVAILABLE = 'available',
  PENDING = 'pending',
  SOLD = 'sold',
}

