// Generated by schema-gen - DO NOT EDIT

/**
 * Health check endpoint
 * @path GET /health
 */
export const getHealthPath = () => '/health' as const;

/**
 * List all pets
 * @path GET /pets
 */
export const listPetsPath = () => '/pets' as const;

/**
 * Create a new pet
 * @path POST /pets
 */
export const createPetPath = () => '/pets' as const;

/**
 * Get a pet by ID
 * @path GET /pets/{petId}
 */
export const getPetPath = (params: { petId: string }) => `/pets/${params.petId}` as const;

/**
 * Update a pet
 * @path PUT /pets/{petId}
 */
export const updatePetPath = (params: { petId: string }) => `/pets/${params.petId}` as const;

/**
 * Partially update a pet
 * @path PATCH /pets/{petId}
 */
export const patchPetPath = (params: { petId: string }) => `/pets/${params.petId}` as const;

/**
 * Delete a pet
 * @path DELETE /pets/{petId}
 */
export const deletePetPath = (params: { petId: string }) => `/pets/${params.petId}` as const;

/**
 * Upload a pet photo
 * @path POST /pets/{petId}/photo
 */
export const uploadPetPhotoPath = (params: { petId: string }) => `/pets/${params.petId}/photo` as const;

/**
 * Search pets with complex criteria
 * @path POST /pets/search
 */
export const searchPetsPath = () => '/pets/search' as const;

/**
 * Create multiple pets
 * @path POST /pets/bulk
 */
export const createPetsBulkPath = () => '/pets/bulk' as const;

/**
 * List all users
 * @path GET /users
 */
export const listUsersPath = () => '/users' as const;

/**
 * Create a new user
 * @path POST /users
 */
export const createUserPath = () => '/users' as const;

/**
 * Get a user by ID
 * @path GET /users/{userId}
 */
export const getUserPath = (params: { userId: number }) => `/users/${params.userId}` as const;

/**
 * Delete a user
 * @path DELETE /users/{userId}
 */
export const deleteUserPath = (params: { userId: number }) => `/users/${params.userId}` as const;

/**
 * Get pets owned by a user
 * @path GET /users/{userId}/pets
 */
export const getUserPetsPath = (params: { userId: number }) => `/users/${params.userId}/pets` as const;

/**
 * Upload a file
 * @path POST /files/upload
 */
export const uploadFilePath = () => '/files/upload' as const;

/**
 * Get file metadata
 * @path GET /files/{fileId}
 */
export const getFilePath = (params: { fileId: string }) => `/files/${params.fileId}` as const;

/**
 * Delete a file
 * @path DELETE /files/{fileId}
 */
export const deleteFilePath = (params: { fileId: string }) => `/files/${params.fileId}` as const;
