// Generated by schema-gen - DO NOT EDIT

import type { UseQueryOptions, UseQueryReturnType, UseMutationOptions, UseMutationReturnType } from '@tanstack/vue-query';
import { useQuery, useMutation } from '@tanstack/vue-query';
import type { MaybeRef } from 'vue';
import { computed, unref } from 'vue';
import { apiClient } from '../lib/client';
import { toFormData } from '../lib/form-data';
import type { CreatePetRequest, CreateUserRequest, FileMetadata, FileUploadRequest, FileUploadResponse, HealthStatus, PatchPetRequest, Pet, PetList, PhotoUploadRequest, PhotoUploadResponse, UpdatePetRequest, User } from './types';
import { PetStatus, UserRole } from './enums';


// ============ GET /health ============

export const getGetHealthQueryKey = () => ['getHealth'] as const;

export type GetHealthQueryKey = ReturnType<typeof getGetHealthQueryKey>;

export const getGetHealthQueryOptions = <TData = HealthStatus, TError = Error>(
  options?: Partial<UseQueryOptions<HealthStatus, TError, TData>>
) => ({
  queryKey: getGetHealthQueryKey(),
  queryFn: () => apiClient<HealthStatus>('/health'),
  ...options,
});

/**
 * Health check endpoint
 * @path GET /health
 */
export const useGetHealth = <TData = HealthStatus, TError = Error>(
  options?: Partial<UseQueryOptions<HealthStatus, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetHealthQueryOptions(options));
};


// ============ GET /pets ============

export interface ListPetsParams {
  limit?: number;
  offset?: number;
  status?: PetStatus;
  tags?: string[];
}

export const getListPetsQueryKey = (params: ListPetsParams) =>
  ['listPets', params.limit, params.offset, params.status, params.tags] as const;

export type ListPetsQueryKey = ReturnType<typeof getListPetsQueryKey>;

export const getListPetsQueryOptions = <TData = PetList, TError = Error>(
  params: MaybeRef<ListPetsParams>,
  options?: Partial<UseQueryOptions<PetList, TError, TData>>
) => ({
  queryKey: computed(() => getListPetsQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const searchParams = new URLSearchParams();
      if (p.limit !== undefined) searchParams.append('limit', String(p.limit));
      if (p.offset !== undefined) searchParams.append('offset', String(p.offset));
      if (p.status !== undefined) searchParams.append('status', String(p.status));
      if (p.tags !== undefined) searchParams.append('tags', String(p.tags));
      const query = searchParams.toString();
      const url = `/pets${query ? `?${query}` : ''}`;
      return apiClient<PetList>(url);
    })(),
  ...options,
});

/**
 * List all pets
 * @path GET /pets
 */
export const useListPets = <TData = PetList, TError = Error>(
  params: MaybeRef<ListPetsParams>,
  options?: Partial<UseQueryOptions<PetList, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getListPetsQueryOptions(params, options));
};


// ============ POST /pets ============

export interface CreatePetVariables {
  data: CreatePetRequest;
}

/**
 * Create a new pet
 * @path POST /pets
 */
export const useCreatePet = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, TError, CreatePetVariables, TContext>>
): UseMutationReturnType<Pet, TError, CreatePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>('/pets', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /pets/{petId} ============

export interface GetPetParams {
  petId: string;
}

export const getGetPetQueryKey = (params: GetPetParams) =>
  ['getPet', params.petId] as const;

export type GetPetQueryKey = ReturnType<typeof getGetPetQueryKey>;

export const getGetPetQueryOptions = <TData = Pet, TError = Error>(
  params: MaybeRef<GetPetParams>,
  options?: Partial<UseQueryOptions<Pet, TError, TData>>
) => ({
  queryKey: computed(() => getGetPetQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const url = `/pets/${p.petId}`;
      return apiClient<Pet>(url);
    })(),
  ...options,
});

/**
 * Get a pet by ID
 * @path GET /pets/{petId}
 */
export const useGetPet = <TData = Pet, TError = Error>(
  params: MaybeRef<GetPetParams>,
  options?: Partial<UseQueryOptions<Pet, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetPetQueryOptions(params, options));
};


// ============ PUT /pets/{petId} ============

export interface UpdatePetVariables {
  petId: string;
  data: UpdatePetRequest;
}

/**
 * Update a pet
 * @path PUT /pets/{petId}
 */
export const useUpdatePet = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, TError, UpdatePetVariables, TContext>>
): UseMutationReturnType<Pet, TError, UpdatePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>(`/pets/${vars.petId}`, { method: 'PUT', body: vars.data }),
    ...options,
  });
};


// ============ PATCH /pets/{petId} ============

export interface PatchPetVariables {
  petId: string;
  data: PatchPetRequest;
}

/**
 * Partially update a pet
 * @path PATCH /pets/{petId}
 */
export const usePatchPet = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, TError, PatchPetVariables, TContext>>
): UseMutationReturnType<Pet, TError, PatchPetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>(`/pets/${vars.petId}`, { method: 'PATCH', body: vars.data }),
    ...options,
  });
};


// ============ DELETE /pets/{petId} ============

export interface DeletePetVariables {
  petId: string;
}

/**
 * Delete a pet
 * @path DELETE /pets/{petId}
 */
export const useDeletePet = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, DeletePetVariables, TContext>>
): UseMutationReturnType<unknown, TError, DeletePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<void>(`/pets/${vars.petId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ POST /pets/{petId}/photo ============

export interface UploadPetPhotoVariables {
  petId: string;
  data: PhotoUploadRequest;
}

/**
 * Upload a pet photo
 * @path POST /pets/{petId}/photo
 */
export const useUploadPetPhoto = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<PhotoUploadResponse, TError, UploadPetPhotoVariables, TContext>>
): UseMutationReturnType<PhotoUploadResponse, TError, UploadPetPhotoVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<PhotoUploadResponse>(`/pets/${vars.petId}/photo`, { method: 'POST', body: toFormData(vars.data, { path: '/pets/{petId}/photo', method: 'POST' }) }),
    ...options,
  });
};


// ============ POST /pets/search ============

export const getSearchPetsQueryKey = () => ['searchPets'] as const;

export type SearchPetsQueryKey = ReturnType<typeof getSearchPetsQueryKey>;

export const getSearchPetsQueryOptions = <TData = PetList, TError = Error>(
  options?: Partial<UseQueryOptions<PetList, TError, TData>>
) => ({
  queryKey: getSearchPetsQueryKey(),
  queryFn: () => apiClient<PetList>('/pets/search'),
  ...options,
});

/**
 * Search pets with complex criteria
 * @path POST /pets/search
 */
export const useSearchPets = <TData = PetList, TError = Error>(
  options?: Partial<UseQueryOptions<PetList, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getSearchPetsQueryOptions(options));
};


// ============ POST /pets/bulk ============

export interface CreatePetsBulkVariables {
  data: CreatePetRequest[];
}

/**
 * Create multiple pets
 * @path POST /pets/bulk
 */
export const useCreatePetsBulk = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet[], TError, CreatePetsBulkVariables, TContext>>
): UseMutationReturnType<Pet[], TError, CreatePetsBulkVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet[]>('/pets/bulk', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /users ============

export interface ListUsersParams {
  role?: UserRole;
}

export const getListUsersQueryKey = (params: ListUsersParams) =>
  ['listUsers', params.role] as const;

export type ListUsersQueryKey = ReturnType<typeof getListUsersQueryKey>;

export const getListUsersQueryOptions = <TData = User[], TError = Error>(
  params: MaybeRef<ListUsersParams>,
  options?: Partial<UseQueryOptions<User[], TError, TData>>
) => ({
  queryKey: computed(() => getListUsersQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const searchParams = new URLSearchParams();
      if (p.role !== undefined) searchParams.append('role', String(p.role));
      const query = searchParams.toString();
      const url = `/users${query ? `?${query}` : ''}`;
      return apiClient<User[]>(url);
    })(),
  ...options,
});

/**
 * List all users
 * @path GET /users
 */
export const useListUsers = <TData = User[], TError = Error>(
  params: MaybeRef<ListUsersParams>,
  options?: Partial<UseQueryOptions<User[], TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getListUsersQueryOptions(params, options));
};


// ============ POST /users ============

export interface CreateUserVariables {
  data: CreateUserRequest;
}

/**
 * Create a new user
 * @path POST /users
 */
export const useCreateUser = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<User, TError, CreateUserVariables, TContext>>
): UseMutationReturnType<User, TError, CreateUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<User>('/users', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /users/{userId} ============

export interface GetUserParams {
  userId: number;
}

export const getGetUserQueryKey = (params: GetUserParams) =>
  ['getUser', params.userId] as const;

export type GetUserQueryKey = ReturnType<typeof getGetUserQueryKey>;

export const getGetUserQueryOptions = <TData = User, TError = Error>(
  params: MaybeRef<GetUserParams>,
  options?: Partial<UseQueryOptions<User, TError, TData>>
) => ({
  queryKey: computed(() => getGetUserQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const url = `/users/${p.userId}`;
      return apiClient<User>(url);
    })(),
  ...options,
});

/**
 * Get a user by ID
 * @path GET /users/{userId}
 */
export const useGetUser = <TData = User, TError = Error>(
  params: MaybeRef<GetUserParams>,
  options?: Partial<UseQueryOptions<User, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetUserQueryOptions(params, options));
};


// ============ DELETE /users/{userId} ============

export interface DeleteUserVariables {
  userId: number;
}

/**
 * Delete a user
 * @path DELETE /users/{userId}
 */
export const useDeleteUser = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, DeleteUserVariables, TContext>>
): UseMutationReturnType<unknown, TError, DeleteUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<void>(`/users/${vars.userId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ GET /users/{userId}/pets ============

export interface GetUserPetsParams {
  userId: number;
  status?: PetStatus;
}

export const getGetUserPetsQueryKey = (params: GetUserPetsParams) =>
  ['getUserPets', params.userId, params.status] as const;

export type GetUserPetsQueryKey = ReturnType<typeof getGetUserPetsQueryKey>;

export const getGetUserPetsQueryOptions = <TData = Pet[], TError = Error>(
  params: MaybeRef<GetUserPetsParams>,
  options?: Partial<UseQueryOptions<Pet[], TError, TData>>
) => ({
  queryKey: computed(() => getGetUserPetsQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const searchParams = new URLSearchParams();
      if (p.status !== undefined) searchParams.append('status', String(p.status));
      const query = searchParams.toString();
      const url = `/users/${p.userId}/pets${query ? `?${query}` : ''}`;
      return apiClient<Pet[]>(url);
    })(),
  ...options,
});

/**
 * Get pets owned by a user
 * @path GET /users/{userId}/pets
 */
export const useGetUserPets = <TData = Pet[], TError = Error>(
  params: MaybeRef<GetUserPetsParams>,
  options?: Partial<UseQueryOptions<Pet[], TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetUserPetsQueryOptions(params, options));
};


// ============ POST /files/upload ============

export interface UploadFileVariables {
  data: FileUploadRequest;
}

/**
 * Upload a file
 * @path POST /files/upload
 */
export const useUploadFile = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<FileUploadResponse, TError, UploadFileVariables, TContext>>
): UseMutationReturnType<FileUploadResponse, TError, UploadFileVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<FileUploadResponse>('/files/upload', { method: 'POST', body: toFormData(vars.data, { path: '/files/upload', method: 'POST' }) }),
    ...options,
  });
};


// ============ GET /files/{fileId} ============

export interface GetFileParams {
  fileId: string;
}

export const getGetFileQueryKey = (params: GetFileParams) =>
  ['getFile', params.fileId] as const;

export type GetFileQueryKey = ReturnType<typeof getGetFileQueryKey>;

export const getGetFileQueryOptions = <TData = FileMetadata, TError = Error>(
  params: MaybeRef<GetFileParams>,
  options?: Partial<UseQueryOptions<FileMetadata, TError, TData>>
) => ({
  queryKey: computed(() => getGetFileQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const url = `/files/${p.fileId}`;
      return apiClient<FileMetadata>(url);
    })(),
  ...options,
});

/**
 * Get file metadata
 * @path GET /files/{fileId}
 */
export const useGetFile = <TData = FileMetadata, TError = Error>(
  params: MaybeRef<GetFileParams>,
  options?: Partial<UseQueryOptions<FileMetadata, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetFileQueryOptions(params, options));
};


// ============ DELETE /files/{fileId} ============

export interface DeleteFileVariables {
  fileId: string;
}

/**
 * Delete a file
 * @path DELETE /files/{fileId}
 */
export const useDeleteFile = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, DeleteFileVariables, TContext>>
): UseMutationReturnType<unknown, TError, DeleteFileVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<void>(`/files/${vars.fileId}`, { method: 'DELETE' }),
    ...options,
  });
};
