// Generated by schema-gen - DO NOT EDIT

import type { UseQueryOptions, UseQueryReturnType, UseMutationOptions, UseMutationReturnType } from '@tanstack/vue-query';
import { useQuery, useMutation } from '@tanstack/vue-query';
import type { MaybeRef } from 'vue';
import { computed, unref } from 'vue';
import { apiClient } from '../lib/client';
import { toFormData } from '../lib/form-data';
import type { ApiResponse, Order, Pet, User } from './types';


// ============ POST /pet ============

export interface AddPetVariables {
  data: Pet;
}

/**
 * Add a new pet to the store
 * @path POST /pet
 */
export const useAddPet = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, TError, AddPetVariables, TContext>>
): UseMutationReturnType<Pet, TError, AddPetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>('/pet', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ PUT /pet ============

export interface UpdatePetVariables {
  data: Pet;
}

/**
 * Update an existing pet
 * @path PUT /pet
 */
export const useUpdatePet = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<Pet, TError, UpdatePetVariables, TContext>>
): UseMutationReturnType<Pet, TError, UpdatePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Pet>('/pet', { method: 'PUT', body: vars.data }),
    ...options,
  });
};


// ============ GET /pet/findByStatus ============

export interface FindPetsByStatusParams {
  status: string[];
}

export const getFindPetsByStatusQueryKey = (params: FindPetsByStatusParams) =>
  ['findPetsByStatus', params.status] as const;

export type FindPetsByStatusQueryKey = ReturnType<typeof getFindPetsByStatusQueryKey>;

export const getFindPetsByStatusQueryOptions = <TData = Pet[], TError = Error>(
  params: MaybeRef<FindPetsByStatusParams>,
  options?: Partial<UseQueryOptions<Pet[], TError, TData>>
) => ({
  queryKey: computed(() => getFindPetsByStatusQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const searchParams = new URLSearchParams();
      if (p.status !== undefined) searchParams.append('status', String(p.status));
      const query = searchParams.toString();
      const url = `/pet/findByStatus${query ? `?${query}` : ''}`;
      return apiClient<Pet[]>(url);
    })(),
  ...options,
});

/**
 * Finds Pets by status
 * @path GET /pet/findByStatus
 */
export const useFindPetsByStatus = <TData = Pet[], TError = Error>(
  params: MaybeRef<FindPetsByStatusParams>,
  options?: Partial<UseQueryOptions<Pet[], TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getFindPetsByStatusQueryOptions(params, options));
};


// ============ GET /pet/findByTags ============

export interface FindPetsByTagsParams {
  tags: string[];
}

export const getFindPetsByTagsQueryKey = (params: FindPetsByTagsParams) =>
  ['findPetsByTags', params.tags] as const;

export type FindPetsByTagsQueryKey = ReturnType<typeof getFindPetsByTagsQueryKey>;

export const getFindPetsByTagsQueryOptions = <TData = Pet[], TError = Error>(
  params: MaybeRef<FindPetsByTagsParams>,
  options?: Partial<UseQueryOptions<Pet[], TError, TData>>
) => ({
  queryKey: computed(() => getFindPetsByTagsQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const searchParams = new URLSearchParams();
      if (p.tags !== undefined) searchParams.append('tags', String(p.tags));
      const query = searchParams.toString();
      const url = `/pet/findByTags${query ? `?${query}` : ''}`;
      return apiClient<Pet[]>(url);
    })(),
  ...options,
});

/**
 * Finds Pets by tags
 * @path GET /pet/findByTags
 */
export const useFindPetsByTags = <TData = Pet[], TError = Error>(
  params: MaybeRef<FindPetsByTagsParams>,
  options?: Partial<UseQueryOptions<Pet[], TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getFindPetsByTagsQueryOptions(params, options));
};


// ============ GET /pet/{petId} ============

export interface GetPetByIdParams {
  petId: number;
}

export const getGetPetByIdQueryKey = (params: GetPetByIdParams) =>
  ['getPetById', params.petId] as const;

export type GetPetByIdQueryKey = ReturnType<typeof getGetPetByIdQueryKey>;

export const getGetPetByIdQueryOptions = <TData = Pet, TError = Error>(
  params: MaybeRef<GetPetByIdParams>,
  options?: Partial<UseQueryOptions<Pet, TError, TData>>
) => ({
  queryKey: computed(() => getGetPetByIdQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const url = `/pet/${p.petId}`;
      return apiClient<Pet>(url);
    })(),
  ...options,
});

/**
 * Find pet by ID
 * @path GET /pet/{petId}
 */
export const useGetPetById = <TData = Pet, TError = Error>(
  params: MaybeRef<GetPetByIdParams>,
  options?: Partial<UseQueryOptions<Pet, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetPetByIdQueryOptions(params, options));
};


// ============ DELETE /pet/{petId} ============

export interface DeletePetVariables {
  petId: number;
}

/**
 * Deletes a pet
 * @path DELETE /pet/{petId}
 */
export const useDeletePet = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, DeletePetVariables, TContext>>
): UseMutationReturnType<unknown, TError, DeletePetVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/pet/${vars.petId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ POST /pet/{petId}/uploadImage ============

export interface UploadFileVariables {
  petId: number;
  data: unknown;
}

/**
 * Uploads an image
 * @path POST /pet/{petId}/uploadImage
 */
export const useUploadFile = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<ApiResponse, TError, UploadFileVariables, TContext>>
): UseMutationReturnType<ApiResponse, TError, UploadFileVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<ApiResponse>(`/pet/${vars.petId}/uploadImage`, { method: 'POST', body: toFormData(vars.data as Record<string, unknown>, { path: '/pet/{petId}/uploadImage', method: 'POST' }) }),
    ...options,
  });
};


// ============ GET /store/inventory ============

export const getGetInventoryQueryKey = () => ['getInventory'] as const;

export type GetInventoryQueryKey = ReturnType<typeof getGetInventoryQueryKey>;

export const getGetInventoryQueryOptions = <TData = unknown, TError = Error>(
  options?: Partial<UseQueryOptions<unknown, TError, TData>>
) => ({
  queryKey: getGetInventoryQueryKey(),
  queryFn: () => apiClient<unknown>('/store/inventory'),
  ...options,
});

/**
 * Returns pet inventories by status
 * @path GET /store/inventory
 */
export const useGetInventory = <TData = unknown, TError = Error>(
  options?: Partial<UseQueryOptions<unknown, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetInventoryQueryOptions(options));
};


// ============ POST /store/order ============

export interface PlaceOrderVariables {
  data: Order;
}

/**
 * Place an order for a pet
 * @path POST /store/order
 */
export const usePlaceOrder = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<Order, TError, PlaceOrderVariables, TContext>>
): UseMutationReturnType<Order, TError, PlaceOrderVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<Order>('/store/order', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /store/order/{orderId} ============

export interface GetOrderByIdParams {
  orderId: number;
}

export const getGetOrderByIdQueryKey = (params: GetOrderByIdParams) =>
  ['getOrderById', params.orderId] as const;

export type GetOrderByIdQueryKey = ReturnType<typeof getGetOrderByIdQueryKey>;

export const getGetOrderByIdQueryOptions = <TData = Order, TError = Error>(
  params: MaybeRef<GetOrderByIdParams>,
  options?: Partial<UseQueryOptions<Order, TError, TData>>
) => ({
  queryKey: computed(() => getGetOrderByIdQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const url = `/store/order/${p.orderId}`;
      return apiClient<Order>(url);
    })(),
  ...options,
});

/**
 * Find purchase order by ID
 * @path GET /store/order/{orderId}
 */
export const useGetOrderById = <TData = Order, TError = Error>(
  params: MaybeRef<GetOrderByIdParams>,
  options?: Partial<UseQueryOptions<Order, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetOrderByIdQueryOptions(params, options));
};


// ============ DELETE /store/order/{orderId} ============

export interface DeleteOrderVariables {
  orderId: number;
}

/**
 * Delete purchase order by ID
 * @path DELETE /store/order/{orderId}
 */
export const useDeleteOrder = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, DeleteOrderVariables, TContext>>
): UseMutationReturnType<unknown, TError, DeleteOrderVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/store/order/${vars.orderId}`, { method: 'DELETE' }),
    ...options,
  });
};


// ============ POST /user ============

export interface CreateUserVariables {
  data: User;
}

/**
 * Create user
 * @path POST /user
 */
export const useCreateUser = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, CreateUserVariables, TContext>>
): UseMutationReturnType<unknown, TError, CreateUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>('/user', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ POST /user/createWithArray ============

export interface CreateUsersWithArrayInputVariables {
  data: User[];
}

/**
 * Creates list of users with given input array
 * @path POST /user/createWithArray
 */
export const useCreateUsersWithArrayInput = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, CreateUsersWithArrayInputVariables, TContext>>
): UseMutationReturnType<unknown, TError, CreateUsersWithArrayInputVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>('/user/createWithArray', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ POST /user/createWithList ============

export interface CreateUsersWithListInputVariables {
  data: User[];
}

/**
 * Creates list of users with given input array
 * @path POST /user/createWithList
 */
export const useCreateUsersWithListInput = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, CreateUsersWithListInputVariables, TContext>>
): UseMutationReturnType<unknown, TError, CreateUsersWithListInputVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>('/user/createWithList', { method: 'POST', body: vars.data }),
    ...options,
  });
};


// ============ GET /user/login ============

export interface LoginUserParams {
  username: string;
  password: string;
}

export const getLoginUserQueryKey = (params: LoginUserParams) =>
  ['loginUser', params.username, params.password] as const;

export type LoginUserQueryKey = ReturnType<typeof getLoginUserQueryKey>;

export const getLoginUserQueryOptions = <TData = string, TError = Error>(
  params: MaybeRef<LoginUserParams>,
  options?: Partial<UseQueryOptions<string, TError, TData>>
) => ({
  queryKey: computed(() => getLoginUserQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const searchParams = new URLSearchParams();
      if (p.username !== undefined) searchParams.append('username', String(p.username));
      if (p.password !== undefined) searchParams.append('password', String(p.password));
      const query = searchParams.toString();
      const url = `/user/login${query ? `?${query}` : ''}`;
      return apiClient<string>(url);
    })(),
  ...options,
});

/**
 * Logs user into the system
 * @path GET /user/login
 */
export const useLoginUser = <TData = string, TError = Error>(
  params: MaybeRef<LoginUserParams>,
  options?: Partial<UseQueryOptions<string, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getLoginUserQueryOptions(params, options));
};


// ============ GET /user/logout ============

export const getLogoutUserQueryKey = () => ['logoutUser'] as const;

export type LogoutUserQueryKey = ReturnType<typeof getLogoutUserQueryKey>;

export const getLogoutUserQueryOptions = <TData = unknown, TError = Error>(
  options?: Partial<UseQueryOptions<unknown, TError, TData>>
) => ({
  queryKey: getLogoutUserQueryKey(),
  queryFn: () => apiClient<unknown>('/user/logout'),
  ...options,
});

/**
 * Logs out current logged in user session
 * @path GET /user/logout
 */
export const useLogoutUser = <TData = unknown, TError = Error>(
  options?: Partial<UseQueryOptions<unknown, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getLogoutUserQueryOptions(options));
};


// ============ GET /user/{username} ============

export interface GetUserByNameParams {
  username: string;
}

export const getGetUserByNameQueryKey = (params: GetUserByNameParams) =>
  ['getUserByName', params.username] as const;

export type GetUserByNameQueryKey = ReturnType<typeof getGetUserByNameQueryKey>;

export const getGetUserByNameQueryOptions = <TData = User, TError = Error>(
  params: MaybeRef<GetUserByNameParams>,
  options?: Partial<UseQueryOptions<User, TError, TData>>
) => ({
  queryKey: computed(() => getGetUserByNameQueryKey(unref(params))),
  queryFn: () => (() => {
      const p = unref(params);
      const url = `/user/${p.username}`;
      return apiClient<User>(url);
    })(),
  ...options,
});

/**
 * Get user by user name
 * @path GET /user/{username}
 */
export const useGetUserByName = <TData = User, TError = Error>(
  params: MaybeRef<GetUserByNameParams>,
  options?: Partial<UseQueryOptions<User, TError, TData>>
): UseQueryReturnType<TData, TError> => {
  return useQuery(getGetUserByNameQueryOptions(params, options));
};


// ============ PUT /user/{username} ============

export interface UpdateUserVariables {
  username: string;
  data: User;
}

/**
 * Updated user
 * @path PUT /user/{username}
 */
export const useUpdateUser = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, UpdateUserVariables, TContext>>
): UseMutationReturnType<unknown, TError, UpdateUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/user/${vars.username}`, { method: 'PUT', body: vars.data }),
    ...options,
  });
};


// ============ DELETE /user/{username} ============

export interface DeleteUserVariables {
  username: string;
}

/**
 * Delete user
 * @path DELETE /user/{username}
 */
export const useDeleteUser = <TError = Error, TContext = unknown>(
  options?: Partial<UseMutationOptions<unknown, TError, DeleteUserVariables, TContext>>
): UseMutationReturnType<unknown, TError, DeleteUserVariables, TContext> => {
  return useMutation({
    mutationFn: (vars) => apiClient<unknown>(`/user/${vars.username}`, { method: 'DELETE' }),
    ...options,
  });
};
