/**
 * Built-in request paths plugin
 *
 * Generates typed path builder functions for each endpoint.
 * Handles path parameters with proper type inference.
 * Each function is individually exported for tree-shaking.
 *
 * Example output:
 * ```typescript
 * export const getUserPath = (params: { userId: string }) => `/users/${params.userId}` as const;
 * export const listUsersPath = () => '/users' as const;
 * ```
 */

import type { Plugin, EndpointNode, ParameterNode, TypeRef } from '@schema-gen/plugin-sdk';

export interface RequestPathsConfig {
  /**
   * Suffix to append to function names
   * @default 'Path'
   */
  suffix?: string;

  /**
   * Output file name
   * @default 'paths.ts'
   */
  fileName?: string;

  /**
   * Include JSDoc comments with path description
   * @default true
   */
  includeJsDoc?: boolean;
}

const requestPaths: Plugin = {
  id: 'request-paths',
  name: 'Request Paths',
  version: '1.0.0',

  emit(ctx) {
    const config: RequestPathsConfig = ctx.config as RequestPathsConfig;
    const suffix = config.suffix ?? 'Path';
    const fileName = config.fileName ?? 'paths.ts';
    const includeJsDoc = config.includeJsDoc ?? true;

    let output = '// Generated by schema-gen - DO NOT EDIT\n\n';

    for (const endpoint of ctx.ast.endpoints) {
      const pathParams = (endpoint.parameters ?? []).filter((p) => p.location === 'path');
      const baseName = getFunctionName(endpoint, ctx.utils);
      const functionName = baseName + suffix;

      // Add JSDoc comment
      if (includeJsDoc && (endpoint.summary || endpoint.description)) {
        const comment = escapeJsDoc(endpoint.summary || endpoint.description || '');
        output += `/**\n * ${comment}\n * @path ${endpoint.method} ${endpoint.path}\n */\n`;
      }

      if (pathParams.length === 0) {
        // No path parameters - simple getter
        output += `export const ${functionName} = () => '${endpoint.path}' as const;\n\n`;
      } else {
        // Has path parameters - generate function with params
        const paramsType = generateParamsType(pathParams);
        const interpolatedPath = generateInterpolatedPath(endpoint.path, pathParams);

        output += `export const ${functionName} = (params: ${paramsType}) => \`${interpolatedPath}\` as const;\n\n`;
      }
    }

    return [
      {
        path: fileName,
        content: output.trimEnd() + '\n',
      },
    ];
  },
};

/**
 * Escape JSDoc special characters
 */
function escapeJsDoc(text: string): string {
  return text.replace(/\*\//g, '*\\/').replace(/\n/g, '\n * ');
}

/**
 * Get the function name for an endpoint
 */
function getFunctionName(
  endpoint: EndpointNode,
  utils: { toCamelCase: (s: string) => string },
): string {
  if (endpoint.operationId) {
    return utils.toCamelCase(endpoint.operationId);
  }

  // Generate name from method + path
  const pathParts = endpoint.path
    .split('/')
    .filter((p) => p && !p.startsWith('{'))
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1));

  return endpoint.method.toLowerCase() + pathParts.join('');
}

/**
 * Generate TypeScript type for path parameters
 */
function generateParamsType(params: ParameterNode[]): string {
  const props = params.map((p) => {
    const tsType = getTypeScriptType(p.typeRef);
    return `${p.name}: ${tsType}`;
  });

  return `{ ${props.join('; ')} }`;
}

/**
 * Get TypeScript type from a TypeRef
 */
function getTypeScriptType(typeRef: TypeRef): string {
  switch (typeRef.kind) {
    case 'primitive':
      if ('primitiveType' in typeRef) {
        switch (typeRef.primitiveType) {
          case 'string':
            return 'string';
          case 'number':
          case 'integer':
            return 'number';
          case 'boolean':
            return 'boolean';
          default:
            return 'string';
        }
      }
      return 'string';
    case 'named':
    case 'enum':
      return typeRef.name;
    case 'array':
      return `${getTypeScriptType(typeRef.items)}[]`;
    default:
      // Path params are typically strings or numbers
      return 'string';
  }
}

/**
 * Generate interpolated path string
 * Converts `/users/{userId}` to `/users/${params.userId}`
 */
function generateInterpolatedPath(path: string, params: ParameterNode[]): string {
  let result = path;

  for (const param of params) {
    // Match both {param} and {param*} style path params
    const pattern = new RegExp(`\\{${param.name}\\*?\\}`, 'g');
    result = result.replace(pattern, `\${params.${param.name}}`);
  }

  return result;
}

export default requestPaths;
