/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Generated file result */
export interface GeneratedFile {
  /** Relative path for the file */
  path: string;
  /** File contents */
  content: string;
  /** Whether to skip formatting */
  skipFormat: boolean;
}
/**
 * Parse an OpenAPI specification and return the AST as JSON
 *
 * @param content - The specification content (JSON or YAML string)
 * @param format - The format: "json" or "yaml" (optional, auto-detected if not provided)
 * @returns The AST as a JSON string
 */
export declare function parseSpecToAst(content: string, format?: string | undefined | null): string;
/**
 * Parse an OpenAPI specification and return the AST as a JavaScript object
 *
 * @param content - The specification content (JSON or YAML string)
 * @param format - The format: "json" or "yaml" (optional, auto-detected if not provided)
 * @returns The AST as a JavaScript object
 */
export declare function parseSpecToObject(
  content: string,
  format?: string | undefined | null,
): SchemaAst;
/**
 * Validate an OpenAPI specification
 *
 * @param content - The specification content (JSON or YAML string)
 * @param format - The format: "json" or "yaml" (optional, auto-detected if not provided)
 * @returns True if valid, throws an error if invalid
 */
export declare function validateSpec(content: string, format?: string | undefined | null): boolean;
/**
 * Generate TypeScript types from an AST
 *
 * @param astJson - The AST as a JSON string
 * @param options - Generation options as a JSON string
 * @returns Array of generated files
 */
export declare function generateTypescriptTypes(
  astJson: string,
  options?: string | undefined | null,
): Array<GeneratedFile>;
/**
 * Generate TypeScript enums from an AST
 *
 * @param astJson - The AST as a JSON string
 * @param options - Generation options as a JSON string
 * @returns Array of generated files
 */
export declare function generateTypescriptEnums(
  astJson: string,
  options?: string | undefined | null,
): Array<GeneratedFile>;
/**
 * Generate constants from an AST
 *
 * @param astJson - The AST as a JSON string
 * @param options - Generation options as a JSON string
 * @returns Array of generated files
 */
export declare function generateConstants(
  astJson: string,
  options?: string | undefined | null,
): Array<GeneratedFile>;
/** Get the schema-gen version */
export declare function getVersion(): string;
/**
 * Full generation pipeline: parse spec → transform → generate
 *
 * @param content - The specification content (JSON or YAML string)
 * @param format - The format: "json" or "yaml" (optional, auto-detected if not provided)
 * @param generators - Array of generator names to run: ["typescript-types", "typescript-enums", "constants"]
 * @param options - Generation options as a JSON string
 * @returns Array of generated files
 */
export declare function generate(
  content: string,
  format: string | undefined | null,
  generators: Array<string>,
  options?: string | undefined | null,
): Array<GeneratedFile>;
