/**
 * @schema-gen/plugin-sdk
 *
 * SDK for creating custom schema-gen plugins.
 *
 * @example
 * ```typescript
 * import { definePlugin, type PluginContext } from '@schema-gen/plugin-sdk';
 *
 * export default definePlugin({
 *   id: 'my-custom-plugin',
 *   name: 'My Custom Plugin',
 *   version: '1.0.0',
 *
 *   async emit(context) {
 *     return [{
 *       path: 'custom.ts',
 *       content: '// Generated by my custom plugin',
 *     }];
 *   },
 * });
 * ```
 */

// Re-export types from core
export type {
	SchemaAst,
	ApiInfo,
	ServerInfo,
	TagNode,
	TypeNode,
	TypeKind,
	PropertyNode,
	TypeRef,
	PrimitiveType,
	EnumNode,
	EnumVariant,
	EndpointNode,
	HttpMethod,
	ParameterNode,
	RequestBodyNode,
	ResponseNode,
	StatusCode,
	MediaTypeContent,
	HeaderNode,
	SecurityRequirement,
} from '@schema-gen/core';

export type { GeneratedFile } from '@schema-gen/core';

/**
 * Plugin definition
 */
export interface Plugin {
	/** Unique plugin identifier */
	id: string;

	/** Plugin display name */
	name: string;

	/** Plugin version */
	version: string;

	/** Dependencies on other plugins (for ordering) */
	dependencies?: string[];

	/** Called once before processing begins */
	onStart?(context: PluginContext): void | Promise<void>;

	/** Called for each type node */
	onType?(node: import('@schema-gen/core').TypeNode, context: PluginContext): import('@schema-gen/core').TypeNode | void;

	/** Called for each enum node */
	onEnum?(node: import('@schema-gen/core').EnumNode, context: PluginContext): import('@schema-gen/core').EnumNode | void;

	/** Called for each endpoint node */
	onEndpoint?(node: import('@schema-gen/core').EndpointNode, context: PluginContext): import('@schema-gen/core').EndpointNode | void;

	/** Called once after all nodes processed, to emit files */
	emit?(context: PluginContext): import('@schema-gen/core').GeneratedFile[] | Promise<import('@schema-gen/core').GeneratedFile[]>;

	/** Called once after all plugins have emitted */
	onEnd?(context: PluginContext): void | Promise<void>;
}

/**
 * Plugin context provided to all plugin hooks
 */
export interface PluginContext {
	/** Full AST for reference */
	ast: import('@schema-gen/core').SchemaAst;

	/** Plugin configuration from user config */
	config: Record<string, unknown>;

	/** Output directory */
	outputDir: string;

	/** Logger */
	log: Logger;

	/** Access to other plugins' shared state */
	shared: Map<string, unknown>;

	/** Helper utilities */
	utils: PluginUtils;
}

/**
 * Logger interface
 */
export interface Logger {
	debug(message: string): void;
	info(message: string): void;
	warn(message: string): void;
	error(message: string): void;
}

/**
 * Plugin utility functions
 */
export interface PluginUtils {
	/** Convert string to PascalCase */
	toPascalCase(s: string): string;

	/** Convert string to camelCase */
	toCamelCase(s: string): string;

	/** Convert string to SCREAMING_SNAKE_CASE */
	toScreamingSnakeCase(s: string): string;

	/** Convert string to snake_case */
	toSnakeCase(s: string): string;

	/** Convert string to kebab-case */
	toKebabCase(s: string): string;

	/** Resolve a TypeRef to its TypeScript string representation */
	typeRefToString(ref: import('@schema-gen/core').TypeRef): string;

	/** Get all endpoints for a tag */
	getEndpointsByTag(tag: string): import('@schema-gen/core').EndpointNode[];

	/** Check if an endpoint is a query (GET, HEAD, OPTIONS) */
	isQuery(endpoint: import('@schema-gen/core').EndpointNode): boolean;

	/** Check if an endpoint is a mutation (POST, PUT, PATCH, DELETE) */
	isMutation(endpoint: import('@schema-gen/core').EndpointNode): boolean;
}

/**
 * Define a plugin with type safety
 *
 * @param plugin - The plugin definition
 * @returns The plugin definition (for type inference)
 */
export function definePlugin(plugin: Plugin): Plugin {
	return plugin;
}

/**
 * Create a plugin context (for testing)
 */
export function createPluginContext(
	ast: import('@schema-gen/core').SchemaAst,
	options?: Partial<PluginContext>,
): PluginContext {
	return {
		ast,
		config: options?.config ?? {},
		outputDir: options?.outputDir ?? './output',
		log: options?.log ?? createConsoleLogger(),
		shared: options?.shared ?? new Map(),
		utils: createPluginUtils(ast),
	};
}

/**
 * Create a console logger
 */
function createConsoleLogger(): Logger {
	return {
		debug: (msg) => console.debug(`[debug] ${msg}`),
		info: (msg) => console.info(`[info] ${msg}`),
		warn: (msg) => console.warn(`[warn] ${msg}`),
		error: (msg) => console.error(`[error] ${msg}`),
	};
}

/**
 * Create plugin utilities
 */
function createPluginUtils(ast: import('@schema-gen/core').SchemaAst): PluginUtils {
	return {
		toPascalCase(s: string): string {
			return s
				.split(/[-_\s.]+/)
				.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
				.join('');
		},

		toCamelCase(s: string): string {
			const pascal = this.toPascalCase(s);
			return pascal.charAt(0).toLowerCase() + pascal.slice(1);
		},

		toScreamingSnakeCase(s: string): string {
			return this.toSnakeCase(s).toUpperCase();
		},

		toSnakeCase(s: string): string {
			return s
				.replace(/([A-Z])/g, '_$1')
				.toLowerCase()
				.replace(/^_/, '')
				.replace(/[-\s.]+/g, '_');
		},

		toKebabCase(s: string): string {
			return this.toSnakeCase(s).replace(/_/g, '-');
		},

		typeRefToString(ref: import('@schema-gen/core').TypeRef): string {
			switch (ref.kind) {
				case 'named':
					return ref.name;
				case 'array':
					return `${this.typeRefToString(ref.items)}[]`;
				case 'primitive':
					return primitiveToString(ref);
				case 'enum':
					return ref.name;
				case 'unknown':
					return 'unknown';
				default:
					return 'unknown';
			}
		},

		getEndpointsByTag(tag: string): import('@schema-gen/core').EndpointNode[] {
			return ast.endpoints.filter((e) => e.tags.includes(tag));
		},

		isQuery(endpoint: import('@schema-gen/core').EndpointNode): boolean {
			return endpoint.queryType === 'query';
		},

		isMutation(endpoint: import('@schema-gen/core').EndpointNode): boolean {
			return endpoint.queryType === 'mutation';
		},
	};
}

/**
 * Convert a primitive type to its TypeScript string representation
 */
function primitiveToString(prim: import('@schema-gen/core').PrimitiveType): string {
	switch (prim.type) {
		case 'string':
			return 'string';
		case 'number':
		case 'integer':
			return 'number';
		case 'boolean':
			return 'boolean';
		case 'null':
			return 'null';
		case 'any':
			return 'unknown';
		default:
			return 'unknown';
	}
}
